[CACertificate]
Name = "RootCA"
Path = "./CA/"
OrganizationName = "bedrich kucera"
Email = "bekucera@gmail.com"
ValidDays = 79000
RenewThresholdDays = 30

[[Certificates]]
Name = "service-api"
Path = "./service-api"
IPs = ["10.0.0.300"]
DNSNames = ["api.example.com"]

[[Certificates]]
Name = "web-frontend"
Path = "./web-frontend"
IPs = []
DNSNames = ["www.example.com", "example.com"]

[CertificatesDefaults]
ValidDays = 20
RenewThresholdDays = 7
OrganizationName = "bedrich kucera"
Email = "bekucera@gmail.com"

