[CACertificate]
Name = "RootCA"
Path = "./certs/CA/"
OrganizationName = "bedrich kucera CA"
Email = "bekucera@gmail.com"
ValidDays = 79000
RenewThresholdDays = 30

[[Certificates]]
Name = "service-api"
Path = "./certs/service-api"
IPs = ["10.0.0.300"]
DNSNames = ["api.example.com"]

[[Certificates]]
Name = "web-frontend"
Path = "./certs/web-frontend"
DNSNames = ["www.example.com", "example.com"]

[CertificatesDefaults]
ValidDays = 20
RenewThresholdDays = 7
OrganizationName = "bedrich kucera"
Email = "bekucera@gmail.com"
