[CACertificate]
Name = "RootCA"
Path = "./certs/CA/"
OrganizationName = "john doe CA"
Email = "johndoe@example.com"
ValidDays = 79000
RenewThresholdDays = 30

# Individual certificates
# This certificate has all the values specified
[[Certificates]]
Name = "service-api"
Path = "./certs/service-api"
OrganizationName = "john doe"
Email = "johndoe@example.com"
IPs = ["10.0.0.200"]
DNSNames = ["api.example.com"]
ValidDays = 50
RenewThresholdDays = 15

# This certificate get default values from CertificatesDefaults
[[Certificates]]
Name = "web-frontend"
Path = "./certs/web-frontend"
DNSNames = ["www.example.com", "example.com"]

# Default values applied to certificates that don’t specify these fields
[CertificatesDefaults]
ValidDays = 20
RenewThresholdDays = 7
OrganizationName = "john doe"
Email = "johndoe@example.com"


